# Generated by Django 4.0.6 on 2022-07-20 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Groceryitems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_date', models.DateField()),
                ('company_name', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('condition', models.CharField(max_length=30)),
                ('brand_name', models.CharField(max_length=30)),
                ('item_name', models.CharField(max_length=50)),
            ],
        ),
    ]
