# Generated by Django 4.0.6 on 2022-07-21 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceryitems', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groceryitems',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
